### PR TITLE
Thoms' changes to abstract

### PR DESCRIPTION
**Pull request by AnthonyLim23**
@thomasholmrod changes to the abstract

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
I prefer the old version as it is clear and flows. 

After reading the new version I am not as clear on what the purpose of this paper is.

**Comment by AnthonyLim23** [comment]
Just spoke to Keith and he did not understand what the new abstract was trying to say.

**Comment by AnthonyLim23** [comment]
Ed also agrees that the old one is better. @DanNixon are you happy for me to just close this?

**Comment by thomasholmrod** [comment]
as long as the abstract reflects the contents - also the new one - I am fine.

**Pull request closed without merging**
